### ISSUE TITLE
Dump file path

### ISSUE THREAD

**Issue by vf-sohail** [toy/dump#20]
Is there any way to specify the dump path? Currently it is in "dump/" . I want to change the path.

**Comment by toy** [comment]
Currently it is hardcoded, so not without changing code.
Seems there are two places (outside of specs): https://github.com/toy/dump/blob/master/lib/dump.rb#L43 and https://github.com/toy/dump/blob/master/lib/dump/snapshot.rb#L12

**Comment by vf-sohail** [comment]
Thanks toy. 

I change the dump path by overriding the create method in dump.rb

def create(options = {})
      setting = Setting.first
      dump = Snapshot.new(options.merge(:dir => File.join(rails_root, setting.backup_path)))
      Writer.create(dump.tmp_path)
      File.rename(dump.tmp_path, dump.tgz_path)
      puts File.basename(dump.tgz_path)
end
